services:
  envialo-web-app:
    image: carlosmca/envialo-web-app:dev
    container_name: envialo-web-app-container
    env_file: .env
    ports:
      - "${APP_PORT:-3000}:3000"
    networks:
      - envialo-network
    restart: always

networks:
  envialo-network:
    external: true
